config/routes.rb
Rails.application.routes.draw do
  root to: 'tasks#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true
    validates :title, length: {maximum: 20}
    validates :memo, length: {maximum: 50}
    validates :start_day, presence: true
    validates :end_day, presence: true

    validate :validate_end_day_after_start_day
    private
    
    def validate_end_day_after_start_day
        if end_day && start_day != nil
            errors.add(:end_day, 'は開始日より後を選択して下さい') if end_day < start_day
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_q, only: [:index, :search]
  
  def index
    @tasks = @q.result
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params.require(:task).permit(:title,:start_day,:end_day,:all_day,:memo))
    if @task.save
      redirect_to tasks_path, notice: "スケジュールを登録しました"
    else
      render "new"
    end
  end

  def show
    @task = Task.find(params[:id])
    
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(params.require(:task).permit(:title,:start_day,:end_day,:all_day,:memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to tasks_path
    else
      render "edit"
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:alert] = "スケジュールを削除しました"
    redirect_to tasks_path
  end

  def search
    @results = @q.result
  end

  private

  def set_q
    @q = Task.ransack(params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <%= yield %>
    <footer>
      <h1 id="date"></h1> 
      
    </footer>
      
    <script>
      today = new Date();
      year = today.getFullYear();
      month = today.getMonth()+1;
      day = today.getDate();
      date_now = document.getElementById('date');
      date_now.innerHTML = "現在の日時：" + year + "年" + month + "月" + day + "日";

      row = tbl1.rows.length - 1;
      date_now.innerHTML += " " + "スケジュール合計：" + row;
    </script>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <% obj.errors.full_messages.each do |message| %>
        <ul>
            <li><%= message %></li>
        </ul>
    <% end %>
<% end %>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/destroy.html.erb
<h1>Tasks#destroy</h1>
<p>Find me in app/views/tasks/destroy.html.erb</p>

app/views/tasks/edit.html.erb
<%= stylesheet_link_tag 'new','common' %>
<h2>スケジュール編集</h2>
<div class="error"><%= render "shared/error", obj: @task %></div>

<%= form_with model: @task, local: true do |f| %>
<table>
    <tr>
        <th><%= f.label :title, "タイトル" %></th>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
        <th><%= f.label :start_day, "開始日" %></th>
        <td><%= f.datetime_field :start_day %></td>
    </tr>
    <tr>
        <th><%= f.label :end_day, "終了日" %></th>
        <td><%= f.datetime_field :end_day %></td>
    </tr>
    <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td><%= f.check_box :all_day %>
            <p>終日の場合はチェックを入れます</p>
        </td>
    </tr>
    <tr>
        <th><%= f.label :memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :memo, size: "40x10" %></td>
    </tr>
        
</table>
<p><%= f.submit "スケジュールの編集を完了する"%></p>
<% end %>
<p><%= link_to "スケジュール一覧に戻る", tasks_path %></p>

app/views/tasks/index.html.erb
<%= stylesheet_link_tag 'common','index' %>
<div class="wrapper">
    <h2>スケジュール一覧</h2>
    <div class="search">
    <%= search_form_for @q, url: search_tasks_path do |f| %>
        <%= f.search_field :title_cont %>
        <%= f.submit '検索' %>
    <% end %>
    </div>
        
    <p class="notice"><%= flash[:notice] %></p>
    <p class="alert"><%= flash[:alert] %></p>

    <table>
        <table id="tbl1">
        <thead>
            <tr>
                <th>ID</th>
                <th><%= sort_link(@q, :title, "タイトル") %></th>
                <th><%= sort_link(@q, :start_day, "開始日") %></th>
                <th><%= sort_link(@q, :end_day, "終了日") %></th>
                <th><%= sort_link(@q, :all_day, "終日") %></th>
                <th>スケジュール更新日時</th>
                <th>確認</th>
                <th>編集</th>
                <th>削除</th>
            </tr>
        </thead>
        <% @tasks.each do |task| %>
        <tbody>
            <tr>
                <td><%= task.id %></td>
                <td><%= task.title %></td>
                <td><%= l task.start_day, format: :short %></td>
                <td><%= l task.end_day, format: :short %></td>
                <td id="all_day">
                    <% if task.all_day == "1" %>
                        <%= "○" %>
                    <% else %>
                        <%= "" %>
                    <% end %>
                </td>
                <td><%= l task.updated_at %></td>
                <td><%= link_to "確認",task_path(task.id) %></td>
                <td><%= link_to "編集",edit_task_path(task.id) %></td>
                <td><%= link_to "削除",task,method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
            </tr>
        </tbody>
        <% end %>
    </table>
    <p><%= link_to "スケジュール新規登録", new_task_path %></p> 
    <div class="push"></div>
</div>

app/views/tasks/new.html.erb
<%= stylesheet_link_tag 'new','common' %>
<h2>スケジュール新規作成</h2>
<div class="error"><%= render "shared/error", obj: @task %></div>

<%= form_with model: @task, local: true do |f| %>
<table>
    <tr>
        <th><%= f.label :title, "タイトル" %></th>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
        <th><%= f.label :start_day, "開始日" %></th>
        <td><%= f.datetime_field :start_day %></td>
    </tr>
    <tr>
        <th><%= f.label :end_day, "終了日" %></th>
        <td><%= f.datetime_field :end_day %></td>
    </tr>
    <tr>
        <th><%= f.label :all_day, "終日" %></th>
        <td><%= f.check_box :all_day %>
            <p>終日の場合はチェックを入れます</p>
        </td>
    </tr>
    <tr>
        <th><%= f.label :memo, "スケジュールメモ" %></th>
        <td><%= f.text_area :memo, size: "40x10" %></td>
    </tr>
    
</table>
<p><%= f.submit "スケジュールを新規登録する"%></p>
<% end %>
<p><%= link_to "スケジュール一覧に戻る", tasks_path %></p>

app/views/tasks/search.html.erb
<%= stylesheet_link_tag 'common','index' %>
<div class="wrapper">
    <h2>検索結果</h2>
    <table>
        <table id="tbl1">
        <thead>
            <tr>
                <th>ID</th>
                <th><%= sort_link(@q, :title, "タイトル") %></th>
                <th><%= sort_link(@q, :start_day, "開始日") %></th>
                <th><%= sort_link(@q, :end_day, "終了日") %></th>
                <th><%= sort_link(@q, :all_day, "終日") %></th>
                <th>スケジュール更新日時</th>
                <th>確認</th>
                <th>編集</th>
                <th>削除</th>
            </tr>
        </thead>
        <% @results.each do |task| %>
        <tbody>
            <tr>
                <td><%= task.id %></td>
                <td><%= task.title %></td>
                <td><%= l task.start_day, format: :short %></td>
                <td><%= l task.end_day, format: :short %></td>
                <td id="all_day">
                    <% if task.all_day == "1" %>
                        <%= "○" %>
                    <% else %>
                        <%= "" %>
                    <% end %>
                </td>
                <td><%= l task.updated_at %></td>
                <td><%= link_to "確認",task_path(task.id) %></td>
                <td><%= link_to "編集",edit_task_path(task.id) %></td>
                <td><%= link_to "削除",task,method: :delete, data: {confirm: "本当に削除しますか？"} %></td>
            </tr>
        </tbody>
        <% end %>
    </table>

    <p><%= link_to "スケジュール新規登録", new_task_path %></p>
    <p><%= link_to "TOPへ戻る", tasks_path %></p>

    <div class="push"></div>
</div>

app/views/tasks/show.html.erb
<%= stylesheet_link_tag 'common','new' %>
<h2>スケジュール詳細</h2>
<table>
    <tr>
        <th>タイトル</th>
        <td><%= @task.title %></td>
    </tr>
    <tr>
        <th>開始日</th>
        <td><%= l @task.start_day %></td>
    </tr>
    <tr>
        <th>終了日</th>
        <td><%= l @task.end_day %></td>
    </tr>
    <tr>
        <th>投稿日時</th>
        <td><%= l @task.created_at %></td>
    </tr>
    <tr>
        <th>終日</th>
        <td>
            <% if @task.all_day == "1" %>
                <%= @task.all_day = "○" %>
            <% else %>
                <%= @task.all_day = "" %>
            <% end %>
        </td>
    </tr>
    <tr>
        <th>スケジュールメモ</th>
        <td><%= simple_format(h(@task.memo), {align: "left"}, sanitize: false, wrapper_tag: "div") %></td>
    </tr>
</table>
<p><%= link_to "スケジュール一覧に戻る", tasks_path %></p>
<p><%= link_to "スケジュールを編集する", edit_task_path %></p>
<p><%= link_to "スケジュールを削除", tasks_path, method: :DELETE %></p>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>